export declare class CustomWebComponent extends HTMLElement {
    private computed;
    private isInstalled;
    private elementId;
    private readonly props;
    private rootNode;
    private store;
    private _customStyleElement;
    private _customStyleContent;
    private _willUpdate;
    private prevProps;
    constructor();
    connectedCallback(): void;
    disconnectedCallback(): void;
    removeAttribute(key: string): void;
    setAttribute(key: string, val: any): void;
    private attrsToProps;
    private initShadowRoot;
    private initCssStyle;
    private beforeUpdate;
    private update;
    private forceUpdate;
    private updateProps;
    private updateSelf;
    private updated;
    private beforeRender;
    private rendered;
    private receiveProps;
    pureRemoveAttribute(key: string): void;
    pureSetAttribute(key: string, val: string): void;
    private fire;
    private uninstall;
}
